### ISSUE TITLE
img-fix-ca.h missing?

### ISSUE THREAD

**Issue by sm7xvd** [JoesCat/gimp-fix-ca#1]
From line 22 of fix-ca.c
`#include "fix-ca-config.h"`
Where is this file?

**Comment by JoesCat** [comment]
fix-ca-config.h is built from fix-ca-config.h.in when you run `./configure`

fix-ca-config.h.in is built from `autoreconf -i;automake` before you run `./configure`

Looking at the code right now - I see what you mean.
I'll make a patch to fix this problem.
Thanks for pointing this out.

**Comment by JoesCat** [comment]
File added to repository.
You can download a new HEAD from https://github.com/JoesCat/gimp-fix-ca.git or just copy the file itself from the main code page.

**Comment by sm7xvd** [comment]
Got it done and working, thanks. 
However, needed to run autoreconf and automake twice, otherwise got an error that m4 directory does not exist. That and sudo make install, the gimptool way throws many errors.

**Comment by JoesCat** [comment]
I'll have to add a file in the m4 directory. The directory gets efficiently forgotten if it's empty.

Good info about the gimptool - I'll need to update instructions.
Closing issue as resolved.
